### ISSUE TITLE
No lo consigo

### ISSUE THREAD

**Issue by gamba85** [rmatelec/drawful-2-ES#1]
Hola, cuando hago el proceso y lo descargo, en el comprimido no viene el archivo asset que debo reemplazar por el original, además me dice que el comprimido está corrupto.
¿Alguna ayuda?
Gracias, un saludo.

**Comment by rmatelec** [comment]
Buenas, el archivo assets hay que sacarlo del directorio en el que está instalado el juego. Lo cargas como se indica en las instrucciones en la web https://mcprebl.firebaseapp.com/, y cargas los ficheros prompts.json y decoys.json de este repositorio para generar el nuevo fichero de assets. 

Si no te sale, relee atentamente las instrucciones.
Saludos!

**Comment by gamba85** [comment]
Hola, sí, se donde está el assets, lo que digo que cuando le doy a descargar tras hacer el proceso, en el comprimido que descargo no hay un assets que pueda reemplazar por el original. Solo están las carpetas content, TalkshowExport, y los archivos Credits.html, jbg.config.jet y PauseDialog.swf.cache. Estos archivos los he copiado a la carpeta del juego. Esto sin descomprimir.

Si intento descomprimir, me da el siguiente error:

! D:\Users\jfrit85\Downloads\new_assets.zip: El archivo está dañado

En el paso 4. pongo los archivos .json en la derecha cada uno en su sitio, pero no dice si tengo que dar al botón <--Put it in de cada uno ni como.

El el 5. dice que pulse en Download ...., pero hay que darle a Purge unused prompts, en principio no entiendo.

Gracias de antemano, un saludo.

**Comment by idest** [comment]
@gamba85 el archivo que descargas es en si el assets.bin, así que no es necesario descomprimirlo, sólo tienes que cambiarle el nombre de new_assets.zip a assets.bin y luego reemplazarlo como dicen las instrucciones. Con respecto a las otras dudas, lo que me funcionó a mi es, luego de seleccionar los archivos decoys.json y prompts.json, apretar el botón "Put it in" de ambos y luego "Download the assets thing", sin apretar "Purge unused prompts", pero esto último no creo que haga una diferencia. Saludos!

**Comment by gamba85** [comment]
> @gamba85 el archivo que descargas es en si el assets.bin, así que no es necesario descomprimirlo, sólo tienes que cambiarle el nombre de new_assets.zip a assets.bin y luego reemplazarlo como dicen las instrucciones. Con respecto a las otras dudas, lo que me funcionó a mi es, luego de seleccionar los archivos decoys.json y prompts.json, apretar el botón "Put it in" de ambos y luego "Download the assets thing", sin apretar "Purge unused prompts", pero esto último no creo que haga una diferencia. Saludos!

EDITO: Ok, veo que solo lo que traduce son las palabras de las preguntas, que es lo importante en realidad, lo vi al ver los archivos. Hice el amago de jugar para verlo. Estaría bien indicarlo. Gracias por la ayuda :) Un saludo.

Gracias por tú comentario, no sabía que el comprimido era el nuevo Assets, eso ya me quedo claro. Pero me temo que sigo sin conseguirlo, por lo menos hasta donde pruebo sigue saliendo en ingles, los menús, la pantalla para que se conecte alguien,... las preguntas no las he probado.
Hago todo el proceso como indica, tampoco tiene mucho, y con lo que me pusiste, pero nada. Subir mi assets, poner los dos archivos json, darle a Put it in, y descargar y renombrar. Pero nada. También he probado con lo de Purge pero nada.

**Comment by rmatelec** [comment]
Bueno @gamba85, al final no está claro si lo has conseguido. Efectivamente, el procedimiento sólo sirve para traducir las frases del juego, no el resto de la interfaz

**Comment by gamba85** [comment]
> Bueno @gamba85, al final no está claro si lo has conseguido. Efectivamente, el procedimiento sólo sirve para traducir las frases del juego, no el resto de la interfaz

Si, lo conseguí, lo que pasa que no sabía que solo era por eso.
