### ISSUE TITLE
Instrucciones para Linux

### ISSUE THREAD

**Issue by yajo** [rmatelec/drawful-2-ES#2]
Buenas, parece que no tienes instrucciones para linux, pero resulta que es lo más fácil.

El archivo decoys.json debe reemplazar al que viene en `$HOME/.local/share/Steam/steamapps/common/Drawful 2/content/Drawful2Decoy.jet` (es un json de texto plano).

El archivo prompts.json debe machacar el archivo `Drawful2Prompt.jet` que se encuentra en esa misma carpeta.

Como son json en texto plano, es fácil sacarlos para poder tener el original y traducirlo, si hiciera falta...

**Comment by yajo** [comment]
Aparte de eso hay que cambiar el formato de los json.

Ambos ficheros tienen este formato: 

```json
{
  "content": [
    {
      "id": 0,
      "text": "algo",
      "x": false
    },
    ....
}
```

La clave `alternateSpellings` no sirve para nada, pero tampoco hace daño si lo dejas ahí.

La clave `"x"` es equivalente a `adultContent`.

Si no se les cambia ese formato, el juego no arranca.

**Comment by rmatelec** [comment]
Incorporo las instrucciones para Linux en el Readme. Gracias

**Comment by pablomancera** [comment]
Confirmo que funciona, pero no siguiendo la guía, hacen falta algunos pasos, a continuación explico qué fue exactamente lo que cambié de cada uno:

Decoy:

1. Cambiar el key `"decoys"` (línea 2) por `"content"`.
2. Reemplazar todos los keys `"adultContent"` por `"x"`.
3. Guardar el archivo como Drawful2Decoy.jet y ponerlo en (depende de la distro)/steamapps/common/Drawful 2/content/

Prompt:

1. cambiar el key `"prompts"` (línea 2) por `"content"`.
2. Reemplazar todos los keys `"adultContent"` por `"x"`.
3. Reemplazar todos los keys `"questionText"` por `"text"`.
4. Guardar el archivo como Drawful2Prompt.jet y ponerlo en (depende de la distro)/steamapps/common/Drawful 2/content/

Gracias a @rmatelec por crear este proyecto y a @Yajo por indicar inicialmente los pasos para hacer que funcione en Linux.

**Comment by rmatelec** [comment]
Gracias @pablomancera 
Para facilitar la vida a los jugadores de Linux, a partir de ahora publicaré también los archivos de Linux listos para usar.
