### ISSUE TITLE
No hay el fichero assets.bin en la dirección especificada en Mac

### ISSUE THREAD

**Issue by pauguri** [rmatelec/drawful-2-ES#3]
Hola, estoy dentro de la carpeta `Drawful 2.app/Contents/Resources` y no hay el fichero `assets.bin`, sino que hay un `Assets.car` que no es aceptado por la web [https://mcprebl.firebaseapp.com/](https://mcprebl.firebaseapp.com/). Tengo que hacer algún paso extra? Gracias.

**Comment by rmatelec** [comment]
Hola, ni idea porque no juego en Mac. A ver si alguien te puede ayudar

**Comment by guillermomuntaner** [comment]
@PauGuri2002 He tenido el mismo problema, pero tiene solución (es aun más fácil!). 

Solo has de ir a `Drawful 2/Contents/Resources/macos/content` y reemplazar los 2 archivos `Drawful2Decoy.jet `& `Drawful2Prompt.jet` con los que hay en el repo.
