### ISSUE TITLE
Error en la propiedad adultContent del prompts.json generado a partir de traducciones

### ISSUE THREAD

**Issue by idest** [rmatelec/drawful-2-ES#4]
Cuando se selecciona `No` en el input `¿Apto para niños?` de la [página para enviar traducciones](https://tools.reinventia.net/drawful2/), se añade la propiedad `"adultContent: "false"` al objeto de `prompts.json` generado (y viceversa), lo que da un resultado precisamente contrario al que se busca.

**Comment by rmatelec** [comment]
Gracias por el aviso, ya está arreglado en el fichero de prompts
